package gd.services.ledDisplay.wirelessProject.dao;

import java.util.Map;

/**
 * Created by 徐文正 on 2019/1/12.
 */
public class FrontPageThemeDAO {
    public static String getMonthTotalHours(Map reqMap) {
        StringBuffer strBuffer = new StringBuffer();
        strBuffer.append("SELECT   order_type, MONTH, MIN (history_date) history_date,                 ")
                .append("         CEIL (SUM (play_time) * 24) total_hour                              ")
                .append("    FROM (SELECT CASE                                                        ")
                .append("                    WHEN start_time <= end_time                              ")
                .append("                       THEN end_time - start_time                            ")
                .append("                    WHEN start_time > end_time                               ")
                .append("                       THEN   end_time                                       ")
                .append("                            - TO_DATE (history_date || ' 00:00:00',          ")
                .append("                                       'yyyy-MM-dd HH24:Mi:ss'               ")
                .append("                                      )                                      ")
                .append("                            + TO_DATE (history_date || ' 23:59:59',          ")
                .append("                                       'yyyy-MM-dd HH24:Mi:ss'               ")
                .append("                                      )                                      ")
                .append("                            - start_time                                     ")
                .append("                 END play_time,                                              ")
                .append("                 DECODE (order_type_dic,                                     ")
                .append("                         '实验', 'SY',                                       ")
                .append("                         '对外广播', 'DW',                                   ")
                .append("                         '中转外', 'DW',                                     ")
                .append("                         'DN'                                                ")
                .append("                        ) order_type,                                        ")
                .append("                 history_date, b.param_name MONTH                            ")
                .append("            FROM (SELECT *                                                   ")
                .append("                    FROM wxj_runplan_history_t                               ")
                .append("                   WHERE history_date >                                      ")
                .append("                                 TO_CHAR (ADD_MONTHS (SYSDATE, -11),         ")
                .append("                                          'yyyy-MM')                         ")
                .append("                     AND order_type_dic IN                                   ")
                .append("                            ('实验', '对内广播', '对外广播', '外转中',       ")
                .append("                             '中转外', '地方广播')) a                        ")
                .append("                 LEFT JOIN                                                   ")
                .append("                 (SELECT param_value, param_name                             ")
                .append("                    FROM wxj_common_param_t                                  ")
                .append("                   WHERE param_type = 'month') b                             ")
                .append("                 ON SUBSTR (a.history_date, 6, 2) = b.param_value            ")
                .append("                 )                                                           ")
                .append("GROUP BY order_type, MONTH                                                   ")
                .append("ORDER BY order_type, history_date                                            ");
        return strBuffer.toString();
    }

    public static String getTodayTotalHours(Map reqMap) {
        StringBuffer strBuffer = new StringBuffer();
        strBuffer.append("SELECT   order_type, SUM (total_hour) total_hour                                              ")
                .append("    FROM (                                                                   ")
                .append("          SELECT   order_type,                                                                ")
                .append("                   CEIL (SUM (end_time - start_time) * 24) total_hour                         ")
                .append("              FROM (SELECT trans_code, start_time, end_time, freq,                            ")
                .append("                           program_name, POWER,                                               ")
                .append("                           DECODE (order_type,                                                ")
                .append("                                   'I', 'SY',                                                 ")
                .append("                                   'F', 'DW',                                                 ")
                .append("                                   'M', 'DW',                                                 ")
                .append("                                   'DN'                                                       ")
                .append("                                  ) order_type                                                ")
                .append("                      FROM wxj_runplan_realtime_t                                             ")
                .append("                     WHERE SYSDATE BETWEEN start_date AND end_date                            ")
                .append("                       AND order_type IN ('D', 'S', 'L', 'F', 'M', 'I')                       ")
                .append("                       AND operate IN ('A', 'U')                                              ")
                .append("                       AND run_type =  1                                                      ")
                .append("                       AND days LIKE                                                          ")
                .append("                              '%' || (SELECT TO_CHAR (SYSDATE - 1, 'd')                       ")
                .append("                                        FROM DUAL) || '%')                                    ")
                .append("             WHERE start_time <= end_time                                                     ")
                .append("               AND start_time < SYSDATE                                                       ")
                .append("               AND end_time <= SYSDATE                                                        ")
                .append("          GROUP BY order_type                                                                 ")
                .append("          UNION ALL                                                         ")
                .append("          SELECT   order_type,                                                                ")
                .append("                   CEIL (SUM (SYSDATE - start_time) * 24) total_hour                          ")
                .append("              FROM (SELECT trans_code, start_time, end_time, freq,                            ")
                .append("                           program_name, POWER,                                               ")
                .append("                           DECODE (order_type,                                                ")
                .append("                                   'I', 'SY',                                                 ")
                .append("                                   'F', 'DW',                                                 ")
                .append("                                   'M', 'DW',                                                 ")
                .append("                                   'DN'                                                       ")
                .append("                                  ) order_type                                                ")
                .append("                      FROM wxj_runplan_realtime_t                                             ")
                .append("                     WHERE SYSDATE BETWEEN start_date AND end_date                            ")
                .append("                       AND order_type IN ('D', 'S', 'L', 'F', 'M', 'I')                       ")
                .append("                       AND operate IN ('A', 'U')                                              ")
                .append("                       AND run_type =  1                                                      ")
                .append("                       AND days LIKE                                                          ")
                .append("                              '%' || (SELECT TO_CHAR (SYSDATE - 1, 'd')                       ")
                .append("                                        FROM DUAL) || '%')                                    ")
                .append("             WHERE start_time <= end_time                                                     ")
                .append("               AND start_time < SYSDATE                                                       ")
                .append("               AND end_time > SYSDATE                                                         ")
                .append("          GROUP BY order_type                                                                 ")
                .append("          UNION ALL                                                           ")
                .append("          SELECT   order_type,                                                                ")
                .append("                   CEIL (  SUM (SYSDATE - start_time) * 24                                    ")
                .append("                         +   SUM (  start_time                                                ")
                .append("                                  - TO_DATE (   TO_CHAR (SYSDATE,                             ")
                .append("                                                         'yyyy-MM-dd')                        ")
                .append("                                             || ' 00:00:00',                                  ")
                .append("                                             'yyyy-MM-dd HH24:Mi:ss'                          ")
                .append("                                            )                                                 ")
                .append("                                 )                                                            ")
                .append("                           * 24                                                               ")
                .append("                        ) total_hour                                                          ")
                .append("              FROM (SELECT trans_code, start_time, end_time, freq,                            ")
                .append("                           program_name, POWER,                                               ")
                .append("                           DECODE (order_type,                                                ")
                .append("                                   'I', 'SY',                                                 ")
                .append("                                   'F', 'DW',                                                 ")
                .append("                                   'M', 'DW',                                                 ")
                .append("                                   'DN'                                                       ")
                .append("                                  ) order_type                                                ")
                .append("                      FROM wxj_runplan_realtime_t                                             ")
                .append("                     WHERE SYSDATE BETWEEN start_date AND end_date                            ")
                .append("                       AND order_type IN ('D', 'S', 'L', 'F', 'M', 'I')                       ")
                .append("                       AND operate IN ('A', 'U')                                              ")
                .append("                       AND run_type =  1                                                      ")
                .append("                       AND days LIKE                                                          ")
                .append("                              '%' || (SELECT TO_CHAR (SYSDATE - 1, 'd')                       ")
                .append("                                        FROM DUAL) || '%')                                    ")
                .append("             WHERE start_time > end_time AND start_time <= SYSDATE                            ")
                .append("          GROUP BY order_type                                                                 ")
                .append("          UNION ALL                                                          ")
                .append("          SELECT   order_type,                                                                ")
                .append("                   CEIL (  SUM (  SYSDATE                                                     ")
                .append("                                - TO_DATE (   TO_CHAR (SYSDATE, 'yyyy-MM-dd')                 ")
                .append("                                           || ' 00:00:00',                                    ")
                .append("                                           'yyyy-MM-dd HH24:Mi:ss'                            ")
                .append("                                          )                                                   ")
                .append("                               )                                                              ")
                .append("                         * 24                                                                 ")
                .append("                        ) total_hour                                                          ")
                .append("              FROM (SELECT trans_code, start_time, end_time, freq,                            ")
                .append("                           program_name, POWER,                                               ")
                .append("                           DECODE (order_type,                                                ")
                .append("                                   'I', 'SY',                                                 ")
                .append("                                   'F', 'DW',                                                 ")
                .append("                                   'M', 'DW',                                                 ")
                .append("                                   'DN'                                                       ")
                .append("                                  ) order_type                                                ")
                .append("                      FROM wxj_runplan_realtime_t                                             ")
                .append("                     WHERE SYSDATE BETWEEN start_date AND end_date                            ")
                .append("                       AND order_type IN ('D', 'S', 'L', 'F', 'M', 'I')                       ")
                .append("                       AND operate IN ('A', 'U')                                              ")
                .append("                       AND run_type =  1                                                      ")
                .append("                       AND days LIKE                                                          ")
                .append("                              '%' || (SELECT TO_CHAR (SYSDATE - 1, 'd')                       ")
                .append("                                        FROM DUAL) || '%')                                    ")
                .append("             WHERE start_time > end_time                                                      ")
                .append("               AND start_time > SYSDATE                                                       ")
                .append("               AND end_time > SYSDATE                                                         ")
                .append("          GROUP BY order_type                                                                 ")
                .append("          UNION ALL                                                          ")
                .append("          SELECT   order_type,                                                                ")
                .append("                   CEIL (  SUM (  end_time                                                    ")
                .append("                                - TO_DATE (   TO_CHAR (SYSDATE, 'yyyy-MM-dd')                 ")
                .append("                                           || ' 00:00:00',                                    ")
                .append("                                           'yyyy-MM-dd HH24:Mi:ss'                            ")
                .append("                                          )                                                   ")
                .append("                               )                                                              ")
                .append("                         * 24                                                                 ")
                .append("                        ) total_hour                                                          ")
                .append("              FROM (SELECT trans_code, start_time, end_time, freq,                            ")
                .append("                           program_name, POWER,                                               ")
                .append("                           DECODE (order_type,                                                ")
                .append("                                   'I', 'SY',                                                 ")
                .append("                                   'F', 'DW',                                                 ")
                .append("                                   'M', 'DW',                                                 ")
                .append("                                   'DN'                                                       ")
                .append("                                  ) order_type                                                ")
                .append("                      FROM wxj_runplan_realtime_t                                             ")
                .append("                     WHERE SYSDATE BETWEEN start_date AND end_date                            ")
                .append("                       AND order_type IN ('D', 'S', 'L', 'F', 'M', 'I')                       ")
                .append("                       AND operate IN ('A', 'U')                                              ")
                .append("                       AND run_type =  1                                                      ")
                .append("                       AND days LIKE                                                          ")
                .append("                              '%' || (SELECT TO_CHAR (SYSDATE - 1, 'd')                       ")
                .append("                                        FROM DUAL) || '%')                                    ")
                .append("             WHERE start_time > end_time                                                      ")
                .append("               AND start_time > SYSDATE                                                       ")
                .append("               AND end_time <= SYSDATE                                                        ")
                .append("          GROUP BY order_type)                                                                ")
                .append("GROUP BY order_type                                                                           ");
        return strBuffer.toString();
    }

    public static String getMonthStopSeconds(Map reqMap) {
        StringBuffer strBuffer = new StringBuffer();
        strBuffer.append("SELECT   MONTH, MIN (accident_date) accident_date,                           ")
                .append("         SUM (stop_seconds) stop_seconds                                     ")
                .append("    FROM (SELECT accident_date, stop_seconds, param_name MONTH               ")
                .append("            FROM (SELECT TO_CHAR (accident_date, 'yyyy-MM') accident_date,   ")
                .append("                         stop_seconds                                        ")
                .append("                    FROM wxj_accident_info_t                                 ")
                .append("                   WHERE accident_date >                                     ")
                .append("                            TO_DATE (TO_CHAR (ADD_MONTHS (SYSDATE, -11),     ")
                .append("                                              'yyyy-MM'                      ")
                .append("                                             ),                              ")
                .append("                                     'yyyy-MM'                               ")
                .append("                                    )) a                                     ")
                .append("                 LEFT JOIN                                                   ")
                .append("                 (SELECT param_value, param_name                             ")
                .append("                    FROM wxj_common_param_t                                  ")
                .append("                   WHERE param_type = 'month') b                             ")
                .append("                 ON SUBSTR (a.accident_date, 6, 2) = b.param_value           ")
                .append("                 )                                                           ")
                .append("GROUP BY MONTH                                                               ")
                .append("ORDER BY accident_date                                                       ");
        return strBuffer.toString();
    }

    public static String getTodayTotalTasks(Map reqMap) {
        StringBuffer strBuffer = new StringBuffer();
        strBuffer.append("SELECT total.param_value order_type, NVL (done.task_done, 0) task_done,                  ")
                .append("       NVL (doing.task_doing, 0) task_doing,                                             ")
                .append("       NVL (doing.freq_doing, 0) freq_doing,                                             ")
                .append("       NVL (doing.program_doing, 0) program_doing,                                       ")
                .append("       NVL (doing.trans_doing, 0) trans_doing,                                           ")
                .append("       NVL (doing.power_doing, 0) power_doing,                                           ")
                .append("       NVL (todo.task_todo, 0) task_todo                                                 ")
                .append("  FROM (SELECT *                                                                         ")
                .append("          FROM wxj_common_param_t                                                        ")
                .append("         WHERE param_type = 'order_type') total                                          ")
                .append("       LEFT JOIN                                                                         ")
                .append("       (SELECT   order_type, COUNT (*) task_done                                         ")
                .append("            FROM (SELECT trans_code, start_time, end_time, freq, program_name,           ")
                .append("                         POWER,                                                          ")
                .append("                         DECODE (order_type,                                             ")
                .append("                                 'I', 'SY',                                              ")
                .append("                                 'F', 'DW',                                              ")
                .append("                                 'M', 'DW',                                              ")
                .append("                                 'DN'                                                    ")
                .append("                                ) order_type                                             ")
                .append("                    FROM wxj_runplan_realtime_t                                          ")
                .append("                   WHERE SYSDATE BETWEEN start_date AND end_date                         ")
                .append("                     AND order_type IN ('D', 'S', 'L', 'F', 'M', 'I')                    ")
                .append("                     AND operate IN ('A', 'U')                                           ")
                .append("                     AND run_type = 1                                                    ")
                .append("                     AND days LIKE                                                       ")
                .append("                              '%' || (SELECT TO_CHAR (SYSDATE - 1, 'd')                  ")
                .append("                                        FROM DUAL) || '%'                                ")
                .append("                     AND (   (    (start_time <= end_time)                               ")
                .append("                              AND (SYSDATE > end_time)                                   ")
                .append("                             )                                                           ")
                .append("                          OR (    (start_time > end_time)                                ")
                .append("                              AND (SYSDATE > end_time)                                   ")
                .append("                             )                                                           ")
                .append("                         ))                                                              ")
                .append("        GROUP BY order_type) done ON done.order_type = total.param_value                 ")
                .append("       LEFT JOIN                                                                         ")
                .append("       (SELECT   order_type, COUNT (DISTINCT freq) freq_doing,                           ")
                .append("                 COUNT (DISTINCT program_name) program_doing,                            ")
                .append("                 COUNT (DISTINCT trans_code) trans_doing,                                ")
                .append("                 SUM (power) power_doing, COUNT  (*) task_doing                          ")
                .append("            FROM (SELECT trans_code, start_time, end_time, freq, program_name,           ")
                .append("                         POWER,                                                          ")
                .append("                         DECODE (order_type,                                             ")
                .append("                                 'I', 'SY',                                              ")
                .append("                                 'F', 'DW',                                              ")
                .append("                                 'M', 'DW',                                              ")
                .append("                                 'DN'                                                    ")
                .append("                                ) order_type                                             ")
                .append("                    FROM wxj_runplan_realtime_t                                          ")
                .append("                   WHERE SYSDATE BETWEEN start_date AND end_date                         ")
                .append("                     AND order_type IN ('D', 'S', 'L', 'F', 'M', 'I')                    ")
                .append("                     AND operate IN ('A', 'U')                                           ")
                .append("                     AND run_type = 1                                                    ")
                .append("                     AND days LIKE                                                       ")
                .append("                              '%' || (SELECT TO_CHAR (SYSDATE - 1, 'd')                  ")
                .append("                                        FROM DUAL) || '%'                                ")
                .append("                     AND trans_code IN (SELECT trans_code                                ")
                .append("                                          FROM wxj_transmitter_status_t                  ")
                .append("                                         WHERE work_status = '10')                       ")
                .append("                     AND (   (    (start_time <= end_time)                               ")
                .append("                              AND (SYSDATE BETWEEN start_time AND end_time)              ")
                .append("                             )                                                           ")
                .append("                          OR (    (start_time > end_time)                                ")
                .append("                              AND (SYSDATE >= start_time                                 ")
                .append("                                   OR SYSDATE <= end_time                                ")
                .append("                                  )                                                      ")
                .append("                             )                                                           ")
                .append("                         ))                                                              ")
                .append("        GROUP BY order_type) doing ON doing.order_type = total.param_value               ")
                .append("       LEFT JOIN                                                                         ")
                .append("       (SELECT   order_type, COUNT (*) task_todo                                         ")
                .append("            FROM (SELECT trans_code, start_time, end_time, freq, program_name,           ")
                .append("                         POWER,                                                          ")
                .append("                         DECODE (order_type,                                             ")
                .append("                                 'I', 'SY',                                              ")
                .append("                                 'F', 'DW',                                              ")
                .append("                                 'M', 'DW',                                              ")
                .append("                                 'DN'                                                    ")
                .append("                                ) order_type                                             ")
                .append("                    FROM wxj_runplan_realtime_t                                          ")
                .append("                   WHERE SYSDATE BETWEEN start_date AND end_date                         ")
                .append("                     AND order_type IN ('D', 'S', 'L', 'F', 'M', 'I')                    ")
                .append("                     AND operate IN ('A', 'U')                                           ")
                .append("                     AND run_type = 1                                                    ")
                .append("                     AND days LIKE                                                       ")
                .append("                              '%' || (SELECT TO_CHAR (SYSDATE - 1, 'd')                  ")
                .append("                                        FROM DUAL) || '%'                                ")
                .append("                     AND (   (    (start_time <= end_time)                               ")
                .append("                              AND (SYSDATE < start_time)                                 ")
                .append("                             )                                                           ")
                .append("                          OR (    (start_time > end_time)                                ")
                .append("                              AND (SYSDATE < start_time AND SYSDATE > end_time           ")
                .append("                                  )                                                      ")
                .append("                             )                                                           ")
                .append("                         ))                                                              ")
                .append("        GROUP BY order_type) todo ON todo.order_type = total.param_value                 ");
        return strBuffer.toString();
    }

    public static String getRealtimeBusiOrderInfo(Map reqMap) {
        StringBuffer strBuffer = new StringBuffer();
        strBuffer.append("SELECT *                                                                          ")
                .append("  FROM (SELECT COUNT (DISTINCT order_code) year_order_count,                      ")
                .append("               CEIL (SUM (end_time - start_time) * 24) year_hour_count            ")
                .append("          FROM (SELECT order_code, start_time,                                    ")
                .append("                       CASE                                                       ")
                .append("                          WHEN SYSDATE > end_time                                 ")
                .append("                             THEN end_time                                        ")
                .append("                          ELSE SYSDATE                                            ")
                .append("                       END end_time                                               ")
                .append("                  FROM wxj_busiorder_detail_history_t                             ")
                .append("                 WHERE status_date >                                              ")
                .append("                                   TO_DATE (TO_CHAR (SYSDATE, 'yyyy'), 'yyyy')    ")
                .append("                   AND SYSDATE >= start_time                                      ")
                .append("                   AND start_time < = end_time                                    ")
                .append("                   AND LENGTH (station_code) = 2))                                ")
                .append("       JOIN                                                                       ")
                .append("       (SELECT COUNT (DISTINCT order_code) today_order_count,                     ")
                .append("               CEIL (SUM (end_time - start_time) * 24) today_hour_count           ")
                .append("          FROM (SELECT order_code, start_time,                                    ")
                .append("                       CASE                                                       ")
                .append("                          WHEN SYSDATE > end_time                                 ")
                .append("                             THEN end_time                                        ")
                .append("                          ELSE SYSDATE                                            ")
                .append("                       END end_time                                               ")
                .append("                  FROM wxj_busiorder_detail_realtime                              ")
                .append("                 WHERE status_date >                                              ")
                .append("                                   TO_DATE (TO_CHAR (SYSDATE, 'yyyy'), 'yyyy')    ")
                .append("                   AND SYSDATE >= start_time                                      ")
                .append("                   AND start_time < = end_time                                    ")
                .append("                   AND LENGTH (station_code) = 2)) ON 1 = 1                       ");
        return strBuffer.toString();
    }

    public static String getSlideShowBusiOrder(Map reqMap) {
        StringBuffer strBuffer = new StringBuffer();
        strBuffer.append("SELECT *                                                                        ")
                .append("  FROM (SELECT   a.order_code_dic order_name, a.send_dept, a.sender,            ")
                .append("                 b.station_name receive_station, a.receiver, b.station_name,    ")
                .append("                    DECODE (SUBSTR (c.trans_code, 4, 1),                        ")
                .append("                            '0', 'A',                                           ")
                .append("                            '1', 'B',                                           ")
                .append("                            '2', 'C',                                           ")
                .append("                            '3', 'D',                                           ")
                .append("                            '4', 'E',                                           ")
                .append("                            '5', 'F',                                           ")
                .append("                            '6', 'G',                                           ")
                .append("                            '7', 'H',                                           ")
                .append("                            'ERROR'                                             ")
                .append("                           )                                                    ")
                .append("                 || SUBSTR (c.trans_code, 5) transmitter,                       ")
                .append("                 a.status_date                                                  ")
                .append("            FROM (SELECT *                                                      ")
                .append("                    FROM wxj_busiorder_total_realtime                           ")
                .append("                   WHERE LENGTH (station_code) = 2) a                           ")
                .append("                 LEFT JOIN                                                      ")
                .append("                 wxj_station_info_t b ON a.station_code = b.station_id          ")
                .append("                 LEFT JOIN wxj_busiorder_detail_realtime c                      ")
                .append("                 ON a.order_code = c.order_code                                 ")
                .append("        ORDER BY status_date DESC)                                              ")
                .append(" WHERE station_name IS NOT NULL AND LENGTH (transmitter) = 3 AND ROWNUM < 11    ");
        return strBuffer.toString();
    }

    public static String getNetWorkCheckInfo(Map reqMap) {
        StringBuffer strBuffer = new StringBuffer();
        strBuffer.append("SELECT SUM (access_count) access_count, SUM (virus_count) virus_count, ")
                .append("       SUM (mole_count) mole_count, SUM (bug_count) bug_count          ")
                .append("  FROM wxj_network_check_t                                             ");
        return strBuffer.toString();
    }

    public static String getRealTimeRunplanInfo(Map reqMap) {
        StringBuffer strBuffer = new StringBuffer();
        strBuffer.append("SELECT SUM (freq_doing) freq_count, SUM (trans_doing) trans_count,                   ")
                .append("       SUM (power_doing) power_count                                                 ")
                .append("  FROM (SELECT total.param_value order_type,                                         ")
                .append("               NVL (doing.freq_doing, 0) freq_doing,                                 ")
                .append("               NVL (doing.power_doing, 0) power_doing,                               ")
                .append("               NVL (doing.trans_doing, 0) trans_doing                                ")
                .append("          FROM (SELECT *                                                             ")
                .append("                  FROM wxj_common_param_t                                            ")
                .append("                 WHERE param_type = 'order_type') total                              ")
                .append("               LEFT JOIN                                                             ")
                .append("               (SELECT   order_type, COUNT (DISTINCT freq) freq_doing,               ")
                .append("                         COUNT (DISTINCT program_name) program_doing,                ")
                .append("                         COUNT (DISTINCT trans_code) trans_doing,                    ")
                .append("                         SUM (POWER) power_doing, COUNT (*) task_doing               ")
                .append("                    FROM (SELECT trans_code, start_time, end_time, freq,             ")
                .append("                                 program_name, POWER,                                ")
                .append("                                 DECODE (order_type,                                 ")
                .append("                                         'I', 'SY',                                  ")
                .append("                                         'F', 'DW',                                  ")
                .append("                                         'M', 'DW',                                  ")
                .append("                                         'DN'                                        ")
                .append("                                        ) order_type                                 ")
                .append("                            FROM wxj_runplan_realtime_t                              ")
                .append("                           WHERE SYSDATE BETWEEN start_date AND end_date             ")
                .append("                             AND order_type IN ('D', 'S', 'L', 'F', 'M', 'I')        ")
                .append("                             AND operate IN ('A', 'U')                               ")
                .append("                             AND run_type = 1                                        ")
                .append("                             AND days LIKE                                           ")
                .append("                                       '%'                                           ")
                .append("                                    || (SELECT TO_CHAR (SYSDATE - 1, 'd')            ")
                .append("                                          FROM DUAL)                                 ")
                .append("                                    || '%'                                           ")
                .append("                             AND trans_code IN (SELECT trans_code                    ")
                .append("                                                  FROM wxj_transmitter_status_t      ")
                .append("                                                 WHERE work_status = '10')           ")
                .append("                             AND (   (    (start_time <= end_time)                   ")
                .append("                                      AND (SYSDATE BETWEEN start_time AND end_time   ")
                .append("                                          )                                          ")
                .append("                                     )                                               ")
                .append("                                  OR (    (start_time > end_time)                    ")
                .append("                                      AND (   SYSDATE >= start_time                  ")
                .append("                                           OR SYSDATE <= end_time                    ")
                .append("                                          )                                          ")
                .append("                                     )                                               ")
                .append("                                 ))                                                  ")
                .append("                GROUP BY order_type) doing                                           ")
                .append("               ON doing.order_type = total.param_value                               ")
                .append("               )                                                                     ");
        return strBuffer.toString();
    }

    public static String getStationNetworkInfo(Map reqMap) {
        StringBuffer strBuffer = new StringBuffer();
        strBuffer.append("SELECT a.station_code, a.ping_status, b.bandwidth_used, b.bandwidth_unused  ")
                .append("  FROM wxj_station_network_info_t a                                         ")
                .append("       JOIN                                                                 ")
                .append("       (SELECT CEIL (SUM (bandwidth_used)) bandwidth_used,                  ")
                .append("               CEIL (SUM (bandwidth_unused)) bandwidth_unused               ")
                .append("          FROM wxj_station_network_info_t) b ON 1 = 1                       ");
        return strBuffer.toString();
    }
}
