package gd.services.ledDisplay.wirelessProject.dao;

import java.util.Map;

/**
 * Created by 徐文正 on 2019/1/12.
 */
public class FrontPageThemeDAO {
    public static String getMonthToalHours(Map reqMap) {
        StringBuffer strBuffer = new StringBuffer();
        strBuffer.append("SELECT   order_type, MONTH, MIN (history_date) history_date,                 ")
                .append("         CEIL (SUM (play_time) * 24) total_hour                              ")
                .append("    FROM (SELECT CASE                                                        ")
                .append("                    WHEN start_time <= end_time                              ")
                .append("                       THEN end_time - start_time                            ")
                .append("                    WHEN start_time > end_time                               ")
                .append("                       THEN   end_time                                       ")
                .append("                            - TO_DATE (history_date || ' 00:00:00',          ")
                .append("                                       'yyyy-MM-dd HH24:Mi:ss'               ")
                .append("                                      )                                      ")
                .append("                            + TO_DATE (history_date || ' 23:59:59',          ")
                .append("                                       'yyyy-MM-dd HH24:Mi:ss'               ")
                .append("                                      )                                      ")
                .append("                            - start_time                                     ")
                .append("                 END play_time,                                              ")
                .append("                 DECODE (order_type_dic,                                     ")
                .append("                         '实验', 'SY',                                       ")
                .append("                         '对外广播', 'DW',                                   ")
                .append("                         '中转外', 'DW',                                     ")
                .append("                         'DN'                                                ")
                .append("                        ) order_type,                                        ")
                .append("                 history_date, b.param_name MONTH                            ")
                .append("            FROM (SELECT *                                                   ")
                .append("                    FROM wxj_runplan_history_t                               ")
                .append("                   WHERE history_date >                                      ")
                .append("                                 TO_CHAR (ADD_MONTHS (SYSDATE, -11),         ")
                .append("                                          'yyyy-MM')                         ")
                .append("                     AND order_type_dic IN                                   ")
                .append("                            ('实验', '对内广播', '对外广播', '外转中',       ")
                .append("                             '中转外', '地方广播')) a                        ")
                .append("                 LEFT JOIN                                                   ")
                .append("                 (SELECT param_value, param_name                             ")
                .append("                    FROM wxj_common_param_t                                  ")
                .append("                   WHERE param_type = 'month') b                             ")
                .append("                 ON SUBSTR (a.history_date, 6, 2) = b.param_value            ")
                .append("                 )                                                           ")
                .append("GROUP BY order_type, MONTH                                                   ")
                .append("ORDER BY order_type, history_date                                            ");
        return strBuffer.toString();
    }

    public static String getTodayToalHours(Map reqMap) {
        StringBuffer strBuffer = new StringBuffer();
        strBuffer.append("  truncate table wxj_runplan_realtime_t ")
                .append("SELECT   order_type, SUM (total_hour) total_hour                                              ")
                .append("    FROM (                                                   --非跨天 播放完成                ")
                .append("          SELECT   order_type,                                                                ")
                .append("                   CEIL (SUM (end_time - start_time) * 24) total_hour                         ")
                .append("              FROM (SELECT trans_code, start_time, end_time, freq,                            ")
                .append("                           program_name, POWER,                                               ")
                .append("                           DECODE (order_type,                                                ")
                .append("                                   'I', 'SY',                                                 ")
                .append("                                   'F', 'DW',                                                 ")
                .append("                                   'M', 'DW',                                                 ")
                .append("                                   'DN'                                                       ")
                .append("                                  ) order_type                                                ")
                .append("                      FROM wxj_runplan_realtime_t                                             ")
                .append("                     WHERE SYSDATE BETWEEN start_date AND end_date                            ")
                .append("                       AND order_type IN ('D', 'S', 'L', 'F', 'M', 'I')                       ")
                .append("                       AND operate IN ('A', 'U')                                              ")
                .append("                       AND run_type =  1                                                      ")
                .append("                       AND days LIKE                                                          ")
                .append("                              '%' || (SELECT TO_CHAR (SYSDATE - 1, 'd')                       ")
                .append("                                        FROM DUAL) || '%')                                    ")
                .append("             WHERE start_time <= end_time                                                     ")
                .append("               AND start_time < SYSDATE                                                       ")
                .append("               AND end_time <= SYSDATE                                                        ")
                .append("          GROUP BY order_type                                                                 ")
                .append("          UNION ALL                                          --非跨天 正在播放                ")
                .append("          SELECT   order_type,                                                                ")
                .append("                   CEIL (SUM (SYSDATE - start_time) * 24) total_hour                          ")
                .append("              FROM (SELECT trans_code, start_time, end_time, freq,                            ")
                .append("                           program_name, POWER,                                               ")
                .append("                           DECODE (order_type,                                                ")
                .append("                                   'I', 'SY',                                                 ")
                .append("                                   'F', 'DW',                                                 ")
                .append("                                   'M', 'DW',                                                 ")
                .append("                                   'DN'                                                       ")
                .append("                                  ) order_type                                                ")
                .append("                      FROM wxj_runplan_realtime_t                                             ")
                .append("                     WHERE SYSDATE BETWEEN start_date AND end_date                            ")
                .append("                       AND order_type IN ('D', 'S', 'L', 'F', 'M', 'I')                       ")
                .append("                       AND operate IN ('A', 'U')                                              ")
                .append("                       AND run_type =  1                                                      ")
                .append("                       AND days LIKE                                                          ")
                .append("                              '%' || (SELECT TO_CHAR (SYSDATE - 1, 'd')                       ")
                .append("                                        FROM DUAL) || '%')                                    ")
                .append("             WHERE start_time <= end_time                                                     ")
                .append("               AND start_time < SYSDATE                                                       ")
                .append("               AND end_time > SYSDATE                                                         ")
                .append("          GROUP BY order_type                                                                 ")
                .append("          UNION ALL                                           --跨天 正在播放1                ")
                .append("          SELECT   order_type,                                                                ")
                .append("                   CEIL (  SUM (SYSDATE - start_time) * 24                                    ")
                .append("                         +   SUM (  start_time                                                ")
                .append("                                  - TO_DATE (   TO_CHAR (SYSDATE,                             ")
                .append("                                                         'yyyy-MM-dd')                        ")
                .append("                                             || ' 00:00:00',                                  ")
                .append("                                             'yyyy-MM-dd HH24:Mi:ss'                          ")
                .append("                                            )                                                 ")
                .append("                                 )                                                            ")
                .append("                           * 24                                                               ")
                .append("                        ) total_hour                                                          ")
                .append("              FROM (SELECT trans_code, start_time, end_time, freq,                            ")
                .append("                           program_name, POWER,                                               ")
                .append("                           DECODE (order_type,                                                ")
                .append("                                   'I', 'SY',                                                 ")
                .append("                                   'F', 'DW',                                                 ")
                .append("                                   'M', 'DW',                                                 ")
                .append("                                   'DN'                                                       ")
                .append("                                  ) order_type                                                ")
                .append("                      FROM wxj_runplan_realtime_t                                             ")
                .append("                     WHERE SYSDATE BETWEEN start_date AND end_date                            ")
                .append("                       AND order_type IN ('D', 'S', 'L', 'F', 'M', 'I')                       ")
                .append("                       AND operate IN ('A', 'U')                                              ")
                .append("                       AND run_type =  1                                                      ")
                .append("                       AND days LIKE                                                          ")
                .append("                              '%' || (SELECT TO_CHAR (SYSDATE - 1, 'd')                       ")
                .append("                                        FROM DUAL) || '%')                                    ")
                .append("             WHERE start_time > end_time AND start_time <= SYSDATE                            ")
                .append("          GROUP BY order_type                                                                 ")
                .append("          UNION ALL                                           --跨天 正在播放2                ")
                .append("          SELECT   order_type,                                                                ")
                .append("                   CEIL (  SUM (  SYSDATE                                                     ")
                .append("                                - TO_DATE (   TO_CHAR (SYSDATE, 'yyyy-MM-dd')                 ")
                .append("                                           || ' 00:00:00',                                    ")
                .append("                                           'yyyy-MM-dd HH24:Mi:ss'                            ")
                .append("                                          )                                                   ")
                .append("                               )                                                              ")
                .append("                         * 24                                                                 ")
                .append("                        ) total_hour                                                          ")
                .append("              FROM (SELECT trans_code, start_time, end_time, freq,                            ")
                .append("                           program_name, POWER,                                               ")
                .append("                           DECODE (order_type,                                                ")
                .append("                                   'I', 'SY',                                                 ")
                .append("                                   'F', 'DW',                                                 ")
                .append("                                   'M', 'DW',                                                 ")
                .append("                                   'DN'                                                       ")
                .append("                                  ) order_type                                                ")
                .append("                      FROM wxj_runplan_realtime_t                                             ")
                .append("                     WHERE SYSDATE BETWEEN start_date AND end_date                            ")
                .append("                       AND order_type IN ('D', 'S', 'L', 'F', 'M', 'I')                       ")
                .append("                       AND operate IN ('A', 'U')                                              ")
                .append("                       AND run_type =  1                                                      ")
                .append("                       AND days LIKE                                                          ")
                .append("                              '%' || (SELECT TO_CHAR (SYSDATE - 1, 'd')                       ")
                .append("                                        FROM DUAL) || '%')                                    ")
                .append("             WHERE start_time > end_time                                                      ")
                .append("               AND start_time > SYSDATE                                                       ")
                .append("               AND end_time > SYSDATE                                                         ")
                .append("          GROUP BY order_type                                                                 ")
                .append("          UNION ALL                                            --跨天 播放完成                ")
                .append("          SELECT   order_type,                                                                ")
                .append("                   CEIL (  SUM (  end_time                                                    ")
                .append("                                - TO_DATE (   TO_CHAR (SYSDATE, 'yyyy-MM-dd')                 ")
                .append("                                           || ' 00:00:00',                                    ")
                .append("                                           'yyyy-MM-dd HH24:Mi:ss'                            ")
                .append("                                          )                                                   ")
                .append("                               )                                                              ")
                .append("                         * 24                                                                 ")
                .append("                        ) total_hour                                                          ")
                .append("              FROM (SELECT trans_code, start_time, end_time, freq,                            ")
                .append("                           program_name, POWER,                                               ")
                .append("                           DECODE (order_type,                                                ")
                .append("                                   'I', 'SY',                                                 ")
                .append("                                   'F', 'DW',                                                 ")
                .append("                                   'M', 'DW',                                                 ")
                .append("                                   'DN'                                                       ")
                .append("                                  ) order_type                                                ")
                .append("                      FROM wxj_runplan_realtime_t                                             ")
                .append("                     WHERE SYSDATE BETWEEN start_date AND end_date                            ")
                .append("                       AND order_type IN ('D', 'S', 'L', 'F', 'M', 'I')                       ")
                .append("                       AND operate IN ('A', 'U')                                              ")
                .append("                       AND run_type =  1                                                      ")
                .append("                       AND days LIKE                                                          ")
                .append("                              '%' || (SELECT TO_CHAR (SYSDATE - 1, 'd')                       ")
                .append("                                        FROM DUAL) || '%')                                    ")
                .append("             WHERE start_time > end_time                                                      ")
                .append("               AND start_time > SYSDATE                                                       ")
                .append("               AND end_time <= SYSDATE                                                        ")
                .append("          GROUP BY order_type)                                                                ")
                .append("GROUP BY order_type                                                                           ");
        return strBuffer.toString();
    }

    public static String getMonthStopSeconds(Map reqMap) {
        StringBuffer strBuffer = new StringBuffer();
        strBuffer.append("SELECT   MONTH, MIN (accident_date) accident_date,                           ")
                .append("         SUM (stop_seconds) stop_seconds                                     ")
                .append("    FROM (SELECT accident_date, stop_seconds, param_name MONTH               ")
                .append("            FROM (SELECT TO_CHAR (accident_date, 'yyyy-MM') accident_date,   ")
                .append("                         stop_seconds                                        ")
                .append("                    FROM wxj_accident_info_t                                 ")
                .append("                   WHERE accident_date >                                     ")
                .append("                            TO_DATE (TO_CHAR (ADD_MONTHS (SYSDATE, -11),     ")
                .append("                                              'yyyy-MM'                      ")
                .append("                                             ),                              ")
                .append("                                     'yyyy-MM'                               ")
                .append("                                    )) a                                     ")
                .append("                 LEFT JOIN                                                   ")
                .append("                 (SELECT param_value, param_name                             ")
                .append("                    FROM wxj_common_param_t                                  ")
                .append("                   WHERE param_type = 'month') b                             ")
                .append("                 ON SUBSTR (a.accident_date, 6, 2) = b.param_value           ")
                .append("                 )                                                           ")
                .append("GROUP BY MONTH                                                               ")
                .append("ORDER BY accident_date                                                       ");
        return strBuffer.toString();
    }
}
