package gd.services.ledDisplay.wirelessProject.dao;

import java.util.Map;

/**
 * Created by 徐文正 on 2019/1/12.
 */
public class FrontPageThemeDAO {
    public static String getMonthTotalHours(Map reqMap) {
        StringBuffer strBuffer = new StringBuffer();
        strBuffer.append("SELECT   order_type, MONTH, MIN (history_date) history_date,                      ")
                .append("         CEIL (SUM (play_time) * 24) total_hour                                   ")
                .append("    FROM (SELECT CASE                                                             ")
                .append("                    WHEN start_time <= end_time                                   ")
                .append("                       THEN end_time - start_time                                 ")
                .append("                    WHEN start_time > end_time                                    ")
                .append("                       THEN   end_time                                            ")
                .append("                            - TO_DATE (history_date || ' 00:00:00',               ")
                .append("                                       'yyyy-MM-dd HH24:Mi:ss'                    ")
                .append("                                      )                                           ")
                .append("                            + TO_DATE (history_date || ' 23:59:59',               ")
                .append("                                       'yyyy-MM-dd HH24:Mi:ss'                    ")
                .append("                                      )                                           ")
                .append("                            - start_time                                          ")
                .append("                 END play_time,                                                   ")
                .append("                 DECODE (order_type_dic,                                          ")
                .append("                         '实验', 'SY',                                            ")
                .append("                         '对外广播', 'DW',                                        ")
                .append("                         'DN'                                                     ")
                .append("                        ) order_type,                                             ")
                .append("                 history_date, b.param_name MONTH                                 ")
                .append("            FROM (SELECT *                                                        ")
                .append("                    FROM wxj_runplan_history_v                                    ")
                .append("                   WHERE history_date >                                           ")
                .append("                                 TO_CHAR (ADD_MONTHS (SYSDATE, -11),              ")
                .append("                                          'yyyy-MM')                              ")
                .append("                     AND order_type_dic IN ('实验', '对内广播', '对外广播')) a    ")
                .append("                 LEFT JOIN                                                        ")
                .append("                 (SELECT param_value, param_name                                  ")
                .append("                    FROM wxj_common_param_t                                       ")
                .append("                   WHERE param_type = 'month') b                                  ")
                .append("                 ON SUBSTR (a.history_date, 6, 2) = b.param_value                 ")
                .append("                 )                                                                ")
                .append("GROUP BY order_type, MONTH                                                        ")
                .append("ORDER BY order_type, history_date                                                 ");
        return strBuffer.toString();
    }

    public static String getTodayTotalHours(Map reqMap) {
        StringBuffer strBuffer = new StringBuffer();
        strBuffer.append("SELECT   order_type, SUM (total_hour) total_hour                               ")
                .append("    FROM (SELECT   order_type,                                                 ")
                .append("                   CEIL (SUM (end_time - start_time) * 24) total_hour          ")
                .append("              FROM (SELECT trans_code, start_time, end_time, freq,             ")
                .append("                           program_name, POWER,                                ")
                .append("                           DECODE (order_type,                                 ")
                .append("                                   'I', 'SY',                                  ")
                .append("                                   'F', 'DW',                                  ")
                .append("                                   'DN'                                        ")
                .append("                                  ) order_type                                 ")
                .append("                      FROM wxj_runplan_realtime_v                              ")
                .append("                     WHERE SYSDATE BETWEEN start_date AND end_date             ")
                .append("                       AND order_type IN ('D', 'F', 'I')                       ")
                .append("                       AND run_type = 1                                        ")
                .append("                       AND days LIKE                                           ")
                .append("                              '%' || (SELECT TO_CHAR (SYSDATE - 1, 'd')        ")
                .append("                                        FROM DUAL) || '%')                     ")
                .append("             WHERE start_time <= end_time                                      ")
                .append("               AND start_time < SYSDATE                                        ")
                .append("               AND end_time <= SYSDATE                                         ")
                .append("          GROUP BY order_type                                                  ")
                .append("          UNION ALL                                                            ")
                .append("          SELECT   order_type,                                                 ")
                .append("                   CEIL (SUM (SYSDATE - start_time) * 24) total_hour           ")
                .append("              FROM (SELECT trans_code, start_time, end_time, freq,             ")
                .append("                           program_name, POWER,                                ")
                .append("                           DECODE (order_type,                                 ")
                .append("                                   'I', 'SY',                                  ")
                .append("                                   'F', 'DW',                                  ")
                .append("                                   'DN'                                        ")
                .append("                                  ) order_type                                 ")
                .append("                      FROM wxj_runplan_realtime_v                              ")
                .append("                     WHERE SYSDATE BETWEEN start_date AND end_date             ")
                .append("                       AND order_type IN ('D', 'F', 'I')                       ")
                .append("                       AND run_type = 1                                        ")
                .append("                       AND days LIKE                                           ")
                .append("                              '%' || (SELECT TO_CHAR (SYSDATE - 1, 'd')        ")
                .append("                                        FROM DUAL) || '%')                     ")
                .append("             WHERE start_time <= end_time                                      ")
                .append("               AND start_time < SYSDATE                                        ")
                .append("               AND end_time > SYSDATE                                          ")
                .append("          GROUP BY order_type                                                  ")
                .append("          UNION ALL                                                            ")
                .append("          SELECT   order_type,                                                 ")
                .append("                   CEIL (  SUM (SYSDATE - start_time) * 24                     ")
                .append("                         +   SUM (  start_time                                 ")
                .append("                                  - TO_DATE (   TO_CHAR (SYSDATE,              ")
                .append("                                                         'yyyy-MM-dd')         ")
                .append("                                             || ' 00:00:00',                   ")
                .append("                                             'yyyy-MM-dd HH24:Mi:ss'           ")
                .append("                                            )                                  ")
                .append("                                 )                                             ")
                .append("                           * 24                                                ")
                .append("                        ) total_hour                                           ")
                .append("              FROM (SELECT trans_code, start_time, end_time, freq,             ")
                .append("                           program_name, POWER,                                ")
                .append("                           DECODE (order_type,                                 ")
                .append("                                   'I', 'SY',                                  ")
                .append("                                   'F', 'DW',                                  ")
                .append("                                   'DN'                                        ")
                .append("                                  ) order_type                                 ")
                .append("                      FROM wxj_runplan_realtime_v                              ")
                .append("                     WHERE SYSDATE BETWEEN start_date AND end_date             ")
                .append("                       AND order_type IN ('D', 'F', 'I')                       ")
                .append("                       AND run_type = 1                                        ")
                .append("                       AND days LIKE                                           ")
                .append("                              '%' || (SELECT TO_CHAR (SYSDATE - 1, 'd')        ")
                .append("                                        FROM DUAL) || '%')                     ")
                .append("             WHERE start_time > end_time AND start_time <= SYSDATE             ")
                .append("          GROUP BY order_type                                                  ")
                .append("          UNION ALL                                                            ")
                .append("          SELECT   order_type,                                                 ")
                .append("                   CEIL (  SUM (  SYSDATE                                      ")
                .append("                                - TO_DATE (   TO_CHAR (SYSDATE, 'yyyy-MM-dd')  ")
                .append("                                           || ' 00:00:00',                     ")
                .append("                                           'yyyy-MM-dd HH24:Mi:ss'             ")
                .append("                                          )                                    ")
                .append("                               )                                               ")
                .append("                         * 24                                                  ")
                .append("                        ) total_hour                                           ")
                .append("              FROM (SELECT trans_code, start_time, end_time, freq,             ")
                .append("                           program_name, POWER,                                ")
                .append("                           DECODE (order_type,                                 ")
                .append("                                   'I', 'SY',                                  ")
                .append("                                   'F', 'DW',                                  ")
                .append("                                   'DN'                                        ")
                .append("                                  ) order_type                                 ")
                .append("                      FROM wxj_runplan_realtime_v                              ")
                .append("                     WHERE SYSDATE BETWEEN start_date AND end_date             ")
                .append("                       AND order_type IN ('D', 'F', 'I')                       ")
                .append("                       AND run_type = 1                                        ")
                .append("                       AND days LIKE                                           ")
                .append("                              '%' || (SELECT TO_CHAR (SYSDATE - 1, 'd')        ")
                .append("                                        FROM DUAL) || '%')                     ")
                .append("             WHERE start_time > end_time                                       ")
                .append("               AND start_time > SYSDATE                                        ")
                .append("               AND end_time > SYSDATE                                          ")
                .append("          GROUP BY order_type                                                  ")
                .append("          UNION ALL                                                            ")
                .append("          SELECT   order_type,                                                 ")
                .append("                   CEIL (  SUM (  end_time                                     ")
                .append("                                - TO_DATE (   TO_CHAR (SYSDATE, 'yyyy-MM-dd')  ")
                .append("                                           || ' 00:00:00',                     ")
                .append("                                           'yyyy-MM-dd HH24:Mi:ss'             ")
                .append("                                          )                                    ")
                .append("                               )                                               ")
                .append("                         * 24                                                  ")
                .append("                        ) total_hour                                           ")
                .append("              FROM (SELECT trans_code, start_time, end_time, freq,             ")
                .append("                           program_name, POWER,                                ")
                .append("                           DECODE (order_type,                                 ")
                .append("                                   'I', 'SY',                                  ")
                .append("                                   'F', 'DW',                                  ")
                .append("                                   'DN'                                        ")
                .append("                                  ) order_type                                 ")
                .append("                      FROM wxj_runplan_realtime_v                              ")
                .append("                     WHERE SYSDATE BETWEEN start_date AND end_date             ")
                .append("                       AND order_type IN ('D', 'F', 'I')                       ")
                .append("                       AND run_type = 1                                        ")
                .append("                       AND days LIKE                                           ")
                .append("                              '%' || (SELECT TO_CHAR (SYSDATE - 1, 'd')        ")
                .append("                                        FROM DUAL) || '%')                     ")
                .append("             WHERE start_time > end_time                                       ")
                .append("               AND start_time > SYSDATE                                        ")
                .append("               AND end_time <= SYSDATE                                         ")
                .append("          GROUP BY order_type)                                                 ")
                .append("GROUP BY order_type                                                            ");
        return strBuffer.toString();
    }

    public static String getMonthStopSeconds(Map reqMap) {
        StringBuffer strBuffer = new StringBuffer();
        strBuffer.append("SELECT   MONTH, MIN (accident_date) accident_date,                           ")
                .append("         SUM (stop_seconds) stop_seconds                                     ")
                .append("    FROM (SELECT accident_date, stop_seconds, param_name MONTH               ")
                .append("            FROM (SELECT TO_CHAR (accident_date, 'yyyy-MM') accident_date,   ")
                .append("                         stop_seconds                                        ")
                .append("                    FROM wxj_accident_info_t                                 ")
                .append("                   WHERE accident_date >                                     ")
                .append("                            TO_DATE (TO_CHAR (ADD_MONTHS (SYSDATE, -11),     ")
                .append("                                              'yyyy-MM'                      ")
                .append("                                             ),                              ")
                .append("                                     'yyyy-MM'                               ")
                .append("                                    )) a                                     ")
                .append("                 LEFT JOIN                                                   ")
                .append("                 (SELECT param_value, param_name                             ")
                .append("                    FROM wxj_common_param_t                                  ")
                .append("                   WHERE param_type = 'month') b                             ")
                .append("                 ON SUBSTR (a.accident_date, 6, 2) = b.param_value           ")
                .append("                 )                                                           ")
                .append("GROUP BY MONTH                                                               ")
                .append("ORDER BY accident_date                                                       ");
        return strBuffer.toString();
    }

    public static String getTodayTotalTasks(Map reqMap) {
        StringBuffer strBuffer = new StringBuffer();
        strBuffer.append("SELECT total.param_value order_type, NVL (done.task_done, 0) task_done,           ")
                .append("       NVL (doing.task_doing, 0) task_doing,                                      ")
                .append("       NVL (doing.freq_doing, 0) freq_doing,                                      ")
                .append("       NVL (doing.program_doing, 0) program_doing,                                ")
                .append("       NVL (doing.trans_doing, 0) trans_doing,                                    ")
                .append("       NVL (doing.power_doing, 0) power_doing,                                    ")
                .append("       NVL (todo.task_todo, 0) task_todo                                          ")
                .append("  FROM (SELECT *                                                                  ")
                .append("          FROM wxj_common_param_t                                                 ")
                .append("         WHERE param_type = 'order_type') total                                   ")
                .append("       LEFT JOIN                                                                  ")
                .append("       (SELECT   order_type, COUNT (*) task_done                                  ")
                .append("            FROM (SELECT trans_code, start_time, end_time, freq, program_name,    ")
                .append("                         POWER,                                                   ")
                .append("                         DECODE (order_type,                                      ")
                .append("                                 'I', 'SY',                                       ")
                .append("                                 'F', 'DW',                                       ")
                .append("                                 'DN'                                             ")
                .append("                                ) order_type                                      ")
                .append("                    FROM wxj_runplan_realtime_v                                   ")
                .append("                   WHERE SYSDATE BETWEEN start_date AND end_date                  ")
                .append("                     AND order_type IN ('D', 'F', 'I')                            ")
                .append("                     AND run_type = 1                                             ")
                .append("                     AND days LIKE                                                ")
                .append("                              '%' || (SELECT TO_CHAR (SYSDATE - 1, 'd')           ")
                .append("                                        FROM DUAL) || '%'                         ")
                .append("                     AND (   (    (start_time <= end_time)                        ")
                .append("                              AND (SYSDATE > end_time)                            ")
                .append("                             )                                                    ")
                .append("                          OR (    (start_time > end_time)                         ")
                .append("                              AND (SYSDATE > end_time)                            ")
                .append("                             )                                                    ")
                .append("                         ))                                                       ")
                .append("        GROUP BY order_type) done ON done.order_type = total.param_value          ")
                .append("       LEFT JOIN                                                                  ")
                .append("       (SELECT   order_type,                                                      ")
                .append("                 COUNT (DISTINCT trans_code || '-' || freq) freq_doing,           ")
                .append("                 COUNT (DISTINCT program_name) program_doing,                     ")
                .append("                 COUNT (DISTINCT trans_code) trans_doing,                         ")
                .append("                 SUM (POWER) power_doing, COUNT (*) task_doing                    ")
                .append("            FROM (SELECT trans_code, start_time, end_time, freq, program_name,    ")
                .append("                         POWER,                                                   ")
                .append("                         DECODE (order_type,                                      ")
                .append("                                 'I', 'SY',                                       ")
                .append("                                 'F', 'DW',                                       ")
                .append("                                 'DN'                                             ")
                .append("                                ) order_type                                      ")
                .append("                    FROM wxj_runplan_realtime_v                                   ")
                .append("                   WHERE SYSDATE BETWEEN start_date AND end_date                  ")
                .append("                     AND order_type IN ('D', 'F', 'I')                            ")
                .append("                     AND run_type = 1                                             ")
                .append("                     AND days LIKE                                                ")
                .append("                              '%' || (SELECT TO_CHAR (SYSDATE - 1, 'd')           ")
                .append("                                        FROM DUAL) || '%'                         ")
                .append("                     AND (   (    (start_time <= end_time)                        ")
                .append("                              AND (SYSDATE BETWEEN start_time AND end_time)       ")
                .append("                             )                                                    ")
                .append("                          OR (    (start_time > end_time)                         ")
                .append("                              AND (SYSDATE >= start_time                          ")
                .append("                                   OR SYSDATE <= end_time                         ")
                .append("                                  )                                               ")
                .append("                             )                                                    ")
                .append("                         ))                                                       ")
                .append("        GROUP BY order_type) doing ON doing.order_type = total.param_value        ")
                .append("       LEFT JOIN                                                                  ")
                .append("       (SELECT   order_type, COUNT (*) task_todo                                  ")
                .append("            FROM (SELECT trans_code, start_time, end_time, freq, program_name,    ")
                .append("                         POWER,                                                   ")
                .append("                         DECODE (order_type,                                      ")
                .append("                                 'I', 'SY',                                       ")
                .append("                                 'F', 'DW',                                       ")
                .append("                                 'DN'                                             ")
                .append("                                ) order_type                                      ")
                .append("                    FROM wxj_runplan_realtime_v                                   ")
                .append("                   WHERE SYSDATE BETWEEN start_date AND end_date                  ")
                .append("                     AND order_type IN ('D', 'F', 'I')                            ")
                .append("                     AND run_type = 1                                             ")
                .append("                     AND days LIKE                                                ")
                .append("                              '%' || (SELECT TO_CHAR (SYSDATE - 1, 'd')           ")
                .append("                                        FROM DUAL) || '%'                         ")
                .append("                     AND (   (    (start_time <= end_time)                        ")
                .append("                              AND (SYSDATE < start_time)                          ")
                .append("                             )                                                    ")
                .append("                          OR (    (start_time > end_time)                         ")
                .append("                              AND (SYSDATE < start_time AND SYSDATE > end_time    ")
                .append("                                  )                                               ")
                .append("                             )                                                    ")
                .append("                         ))                                                       ")
                .append("        GROUP BY order_type) todo ON todo.order_type = total.param_value          ");
        return strBuffer.toString();
    }

    public static String getRealtimeBusiOrderInfo(Map reqMap) {
        StringBuffer strBuffer = new StringBuffer();
        strBuffer.append("SELECT *                                                                                 ")
                .append("  FROM (SELECT COUNT (DISTINCT order_code) year_order_count,                             ")
                .append("               CEIL (SUM (end_time - start_time) * 24) year_hour_count                   ")
                .append("          FROM (SELECT order_code,                                                       ")
                .append("                       CASE                                                              ")
                .append("                          WHEN status_date > start_time                                  ")
                .append("                             THEN status_date                                            ")
                .append("                          ELSE start_time                                                ")
                .append("                       END start_time,                                                   ")
                .append("                       CASE                                                              ")
                .append("                          WHEN SYSDATE > end_time                                        ")
                .append("                             THEN end_time                                               ")
                .append("                          ELSE SYSDATE                                                   ")
                .append("                       END end_time                                                      ")
                .append("                  FROM wxj_busiorder_detail_history_t                                    ")
                .append("                 WHERE status_date >                                                     ")
                .append("                                   TO_DATE (TO_CHAR (SYSDATE, 'yyyy'), 'yyyy')           ")
                .append("                   AND order_code NOT LIKE '88888%'                                      ")
                .append("                   AND SYSDATE >= start_time                                             ")
                .append("                   AND start_time < = end_time                                           ")
                .append("                   AND LENGTH (station_code) = 2))                                       ")
                .append("       JOIN                                                                              ")
                .append("       (SELECT COUNT (DISTINCT order_code) today_order_count,                            ")
                .append("               CEIL (SUM (end_time - start_time) * 24) today_hour_count                  ")
                .append("          FROM (SELECT order_code,                                                       ")
                .append("                       CASE                                                              ")
                .append("                          WHEN status_date > start_time                                  ")
                .append("                             THEN status_date                                            ")
                .append("                          ELSE start_time                                                ")
                .append("                       END start_time,                                                   ")
                .append("                       CASE                                                              ")
                .append("                          WHEN SYSDATE > end_time                                        ")
                .append("                             THEN end_time                                               ")
                .append("                          ELSE SYSDATE                                                   ")
                .append("                       END end_time                                                      ")
                .append("                  FROM wxj_busiorder_detail_realtime                                     ")
                .append("                 WHERE status_date >                                                     ")
                .append("                                   TO_DATE (TO_CHAR (SYSDATE, 'yyyy'), 'yyyy')           ")
                .append("                   AND order_code NOT LIKE '88888%'                                      ")
                .append("                   AND SYSDATE >= start_time                                             ")
                .append("                   AND start_time < = end_time                                           ")
                .append("                   AND LENGTH (station_code) = 2)) ON 1 = 1                              ");
        return strBuffer.toString();
    }

    public static String getSlideShowBusiOrder(Map reqMap) {
        StringBuffer strBuffer = new StringBuffer();
        strBuffer.append("SELECT *                                                                                             ")
                .append("  FROM (SELECT   busiorder.*, transmitter_status.POWER,                                              ")
                .append("                 transmitter_status.amrp                                                             ")
                .append("            FROM (SELECT a.order_code_dic order_name, a.send_dept, a.sender,                         ")
                .append("                         b.station_name receive_station, a.receiver,                                 ")
                .append("                         b.station_name,                                                             ")
                .append("                            DECODE (SUBSTR (c.trans_code, 4, 1),                                     ")
                .append("                                    '0', 'A',                                                        ")
                .append("                                    '1', 'B',                                                        ")
                .append("                                    '2', 'C',                                                        ")
                .append("                                    '3', 'D',                                                        ")
                .append("                                    '4', 'E',                                                        ")
                .append("                                    '5', 'F',                                                        ")
                .append("                                    '6', 'G',                                                        ")
                .append("                                    '7', 'H',                                                        ")
                .append("                                    'ERROR'                                                          ")
                .append("                                   )                                                                 ")
                .append("                         || SUBSTR (c.trans_code, 5) transmitter,                                    ")
                .append("                         a.status_date                                                               ")
                .append("                    FROM (SELECT *                                                                   ")
                .append("                            FROM wxj_busiorder_total_realtime                                        ")
                .append("                           WHERE LENGTH (station_code) = 2                                        ")
                .append("                           and order_code_dic not like '台%') a                                        ")
                .append("                         LEFT JOIN                                                                   ")
                .append("                         wxj_station_info_t b ON a.station_code = b.station_id                       ")
                .append("                         LEFT JOIN wxj_busiorder_detail_realtime c                                   ")
                .append("                         ON a.order_code = c.order_code                                              ")
                .append("                         ) busiorder                                                                 ")
                .append("                 LEFT JOIN                                                                           ")
                .append("                 (SELECT NVL (id2stationname (station_code),                                         ")
                .append("                              '-1'                                                                   ")
                .append("                             ) station_name,                                                         ")
                .append("                            DECODE (SUBSTR (trans_code, 4, 1),                                       ")
                .append("                                    '0', 'A',                                                        ")
                .append("                                    '1', 'B',                                                        ")
                .append("                                    '2', 'C',                                                        ")
                .append("                                    '3', 'D',                                                        ")
                .append("                                    '4', 'E',                                                        ")
                .append("                                    '5', 'F',                                                        ")
                .append("                                    '6', 'G',                                                        ")
                .append("                                    '7', 'H',                                                        ")
                .append("                                    'ERROR'                                                          ")
                .append("                                   )                                                                 ")
                .append("                         || SUBSTR (trans_code, 5) transmitter,                                      ")
                .append("                         CASE                                                                        ")
                .append("                            WHEN CEIL (POWER) < 0                                                    ")
                .append("                               THEN '0'                                                              ")
                .append("                            WHEN CEIL (POWER) > 100                                                  ")
                .append("                               THEN '100'                                                            ")
                .append("                            ELSE TO_CHAR (CEIL (POWER))                                              ")
                .append("                         END POWER,                                                                  ")
                .append("                         CASE                                                                        ")
                .append("                            WHEN CEIL (amrp) < 0                                                     ")
                .append("                               THEN '0'                                                              ")
                .append("                            WHEN CEIL (amrp) > 100                                                   ")
                .append("                               THEN '100'                                                            ")
                .append("                            ELSE TO_CHAR (CEIL (amrp))                                               ")
                .append("                         END amrp                                                                    ")
                .append("                    FROM wxj_transmitter_status_t                                                    ")
                .append("                   WHERE LENGTH (station_code) = 2 AND LENGTH (trans_code) = 6) transmitter_status   ")
                .append("                 ON transmitter_status.station_name = busiorder.station_name                         ")
                .append("               AND transmitter_status.transmitter = busiorder.transmitter                            ")
                .append("           WHERE busiorder.station_name IS NOT NULL                                                  ")
                .append("             AND LENGTH (busiorder.transmitter) = 3                                                  ")
                .append("        ORDER BY status_date DESC)                                                                   ")
                .append(" WHERE ROWNUM < 2                                                                                   ");
        return strBuffer.toString();
    }

    public static String getNetWorkCheckInfo(Map reqMap) {
        StringBuffer strBuffer = new StringBuffer();
        strBuffer.append("SELECT SUM (access_count) access_count, SUM (virus_count) virus_count, ")
                .append("       SUM (mole_count) mole_count, SUM (bug_count) bug_count          ")
                .append("  FROM wxj_network_check_t                                             ");
        return strBuffer.toString();
    }

    public static String getRealTimeRunplanInfo(Map reqMap) {
        StringBuffer strBuffer = new StringBuffer();
        strBuffer.append("SELECT SUM (freq_doing) freq_count, SUM (trans_doing) trans_count,                     ")
                .append("       SUM (power_doing) power_count                                                   ")
                .append("  FROM (SELECT total.param_value order_type,                                           ")
                .append("               NVL (doing.freq_doing, 0) freq_doing,                                   ")
                .append("               NVL (doing.power_doing, 0) power_doing,                                 ")
                .append("               NVL (doing.trans_doing, 0) trans_doing                                  ")
                .append("          FROM (SELECT *                                                               ")
                .append("                  FROM wxj_common_param_t                                              ")
                .append("                 WHERE param_type = 'order_type') total                                ")
                .append("               LEFT JOIN                                                               ")
                .append("               (SELECT   order_type,                                                   ")
                .append("                         COUNT (DISTINCT trans_code || '-' || freq)                    ")
                .append("                                                                   freq_doing,         ")
                .append("                         COUNT (DISTINCT program_name) program_doing,                  ")
                .append("                         COUNT (DISTINCT trans_code) trans_doing,                      ")
                .append("                         SUM (POWER) power_doing, COUNT (*) task_doing                 ")
                .append("                    FROM (SELECT trans_code, start_time, end_time, freq,               ")
                .append("                                 program_name, POWER,                                  ")
                .append("                                 DECODE (order_type,                                   ")
                .append("                                         'I', 'SY',                                    ")
                .append("                                         'F', 'DW',                                    ")
                .append("                                         'DN'                                          ")
                .append("                                        ) order_type                                   ")
                .append("                            FROM wxj_runplan_realtime_v                                ")
                .append("                           WHERE SYSDATE BETWEEN start_date AND end_date               ")
                .append("                             AND order_type IN ('D', 'F', 'I')                         ")
                .append("                             AND run_type = 1                                          ")
                .append("                             AND days LIKE                                             ")
                .append("                                       '%'                                             ")
                .append("                                    || (SELECT TO_CHAR (SYSDATE - 1, 'd')              ")
                .append("                                          FROM DUAL)                                   ")
                .append("                                    || '%'                                             ")
                .append("                             AND (   (    (start_time <= end_time)                     ")
                .append("                                      AND (SYSDATE BETWEEN start_time AND end_time     ")
                .append("                                          )                                            ")
                .append("                                     )                                                 ")
                .append("                                  OR (    (start_time > end_time)                      ")
                .append("                                      AND (   SYSDATE >= start_time                    ")
                .append("                                           OR SYSDATE <= end_time                      ")
                .append("                                          )                                            ")
                .append("                                     )                                                 ")
                .append("                                 ))                                                    ")
                .append("                GROUP BY order_type) doing                                             ")
                .append("               ON doing.order_type = total.param_value                                 ")
                .append("               )                                                                       ");
        return strBuffer.toString();
    }

    public static String getStationNetworkInfo(Map reqMap) {
        StringBuffer strBuffer = new StringBuffer();
        strBuffer.append("SELECT a.station_code, a.ping_status, b.bandwidth_used, b.bandwidth_unused  ")
                .append("  FROM wxj_station_network_info_t a                                         ")
                .append("       JOIN                                                                 ")
                .append("       (SELECT CEIL (SUM (bandwidth_used)) bandwidth_used,                  ")
                .append("               CEIL (SUM (bandwidth_unused)) bandwidth_unused               ")
                .append("          FROM wxj_station_network_info_t) b ON 1 = 1                       ");
        return strBuffer.toString();
    }

    public static String getRealTimeTransDetailInfo(Map reqMap) {
        StringBuffer strBuffer = new StringBuffer();
        strBuffer.append("SELECT DISTINCT *                                                         ")
                .append("           FROM (SELECT    '机房'                                         ")
                .append("                        || DECODE (SUBSTR (trans_code, 4, 1),             ")
                .append("                                   '0', '甲',                              ")
                .append("                                   '1', '乙',                              ")
                .append("                                   '2', '丙',                              ")
                .append("                                   '3', '丁',                              ")
                .append("                                   '4', '戊',                              ")
                .append("                                   '5', '己',                              ")
                .append("                                   '6', '庚',                              ")
                .append("                                   '7', '辛',                              ")
                .append("                                   'ERROR'                                ")
                .append("                                  ) room,                                 ")
                .append("                        SUBSTR (trans_code, 5) transmitter,               ")
                .append("                        DECODE (SUBSTR (work_status, 1, 1),               ")
                .append("                                '1', '正常',                              ")
                .append("                                '2', '空闲',                              ")
                .append("                                '3', '故障',                              ")
                .append("                                '4', '检修',                              ")
                .append("                                '未知'                                    ")
                .append("                               ) work_status                             ")
                .append("                   FROM wxj_transmitter_status_t                          ")
                .append("                  WHERE station_code IN (SELECT station_id                ")
                .append("                                           FROM wxj_station_info_t        ")
                .append("                                          WHERE station_code = '" + reqMap.get("stationCode") + "')    ")
                .append("                    AND LENGTH (trans_code) = 6)                          ")
                .append("          WHERE room <> '机房ERROR'                                       ")
                .append("       ORDER BY room, transmitter                                         ");
        return strBuffer.toString();
    }

    public static String getStationTaskInfo(Map reqMap) {
        StringBuffer strBuffer = new StringBuffer();
        strBuffer.append("SELECT todo.task_todo, todo.play_time_todo, done.task_done,                                                        ")
                .append("       done.play_time_done, STOP.stop_time, alarm.alarm_count,                                                     ")
                .append("       busiorder.busiorder_count, doing.power_doing                                                                ")
                .append("  FROM (SELECT *                                                                                                   ")
                .append("          FROM wxj_common_param_t                                                                                  ")
                .append("         WHERE param_type = 'today_station_tasks') total                                                           ")
                .append("       LEFT JOIN                                                                                                   ")
                .append("       (SELECT 'today_station_tasks' sql_type, COUNT (*) task_todo,                                                ")
                .append("               NVL (CEIL (SUM (play_time) * 24), 0) play_time_todo                                                 ")
                .append("          FROM (SELECT CASE                                                                                        ")
                .append("                          WHEN start_time <= end_time                                                              ")
                .append("                             THEN end_time - start_time                                                            ")
                .append("                          WHEN start_time > end_time                                                               ")
                .append("                             THEN   end_time                                                                       ")
                .append("                                  - TO_DATE (   TO_CHAR (SYSDATE,                                                  ")
                .append("                                                         'yyyy-MM-dd')                                             ")
                .append("                                             || ' 00:00:00',                                                       ")
                .append("                                             'yyyy-MM-dd HH24:Mi:ss'                                               ")
                .append("                                            )                                                                      ")
                .append("                                  + TO_DATE (   TO_CHAR (SYSDATE,                                                  ")
                .append("                                                         'yyyy-MM-dd')                                             ")
                .append("                                             || ' 23:59:59',                                                       ")
                .append("                                             'yyyy-MM-dd HH24:Mi:ss'                                               ")
                .append("                                            )                                                                      ")
                .append("                                  - start_time                                                                     ")
                .append("                       END play_time                                                                               ")
                .append("                  FROM wxj_runplan_realtime_v                                                                      ")
                .append("                 WHERE station_code IN (SELECT station_id                                                          ")
                .append("                                          FROM wxj_station_info_t                                                  ")
                .append("                                         WHERE station_code = '" + reqMap.get("stationCode") + "')                   ")
                .append("                   AND SYSDATE BETWEEN start_date AND end_date                                                     ")
                .append("                   AND order_type IN ('D', 'F', 'I')                                                               ")
                .append("                   AND run_type = 1                                                                                ")
                .append("                   AND days LIKE                                                                                   ")
                .append("                              '%' || (SELECT TO_CHAR (SYSDATE - 1, 'd')                                            ")
                .append("                                        FROM DUAL) || '%')) todo                                                   ")
                .append("       ON todo.sql_type = total.param_value                                                                        ")
                .append("       LEFT JOIN                                                                                                   ")
                .append("       (SELECT 'today_station_tasks' sql_type,                                                                     ")
                .append("               NVL (SUM (task_done), 0) task_done,                                                                 ")
                .append("               NVL (SUM (play_time), 0) play_time_done                                                             ")
                .append("          FROM (SELECT COUNT (*) task_done,                                                                        ")
                .append("                       CEIL (SUM (end_time - start_time) * 24) play_time                                           ")
                .append("                  FROM (SELECT start_time, end_time                                                                ")
                .append("                          FROM wxj_runplan_realtime_v                                                              ")
                .append("                         WHERE station_code IN (SELECT station_id                                                  ")
                .append("                                                  FROM wxj_station_info_t                                          ")
                .append("                                                 WHERE station_code = '" + reqMap.get("stationCode") + "')           ")
                .append("                           AND SYSDATE BETWEEN start_date AND end_date                                             ")
                .append("                           AND order_type IN ('D', 'F', 'I')                                                       ")
                .append("                           AND run_type = 1                                                                        ")
                .append("                           AND days LIKE                                                                           ")
                .append("                                     '%'                                                                           ")
                .append("                                  || (SELECT TO_CHAR (SYSDATE - 1, 'd')                                            ")
                .append("                                        FROM DUAL)                                                                 ")
                .append("                                  || '%')                                                                          ")
                .append("                 WHERE start_time <= end_time                                                                      ")
                .append("                   AND start_time < SYSDATE                                                                        ")
                .append("                   AND end_time <= SYSDATE                                                                         ")
                .append("                UNION ALL                                                                                          ")
                .append("                SELECT COUNT (*) task_done,                                                                        ")
                .append("                       CEIL (SUM (SYSDATE - start_time) * 24) play_time                                            ")
                .append("                  FROM (SELECT start_time, end_time                                                                ")
                .append("                          FROM wxj_runplan_realtime_v                                                              ")
                .append("                         WHERE station_code IN (SELECT station_id                                                  ")
                .append("                                                  FROM wxj_station_info_t                                          ")
                .append("                                                 WHERE station_code = '" + reqMap.get("stationCode") + "')           ")
                .append("                           AND SYSDATE BETWEEN start_date AND end_date                                             ")
                .append("                           AND order_type IN ('D', 'F', 'I')                                                       ")
                .append("                           AND run_type = 1                                                                        ")
                .append("                           AND days LIKE                                                                           ")
                .append("                                     '%'                                                                           ")
                .append("                                  || (SELECT TO_CHAR (SYSDATE - 1, 'd')                                            ")
                .append("                                        FROM DUAL)                                                                 ")
                .append("                                  || '%')                                                                          ")
                .append("                 WHERE start_time <= end_time                                                                      ")
                .append("                   AND start_time < SYSDATE                                                                        ")
                .append("                   AND end_time > SYSDATE                                                                          ")
                .append("                UNION ALL                                                                                          ")
                .append("                SELECT COUNT (*) task_done,                                                                        ")
                .append("                       CEIL                                                                                        ")
                .append("                           (  SUM (SYSDATE - start_time) * 24                                                      ")
                .append("                            +   SUM (  start_time                                                                  ")
                .append("                                     - TO_DATE (   TO_CHAR (SYSDATE,                                               ")
                .append("                                                            'yyyy-MM-dd'                                           ")
                .append("                                                           )                                                       ")
                .append("                                                || ' 00:00:00',                                                    ")
                .append("                                                'yyyy-MM-dd HH24:Mi:ss'                                            ")
                .append("                                               )                                                                   ")
                .append("                                    )                                                                              ")
                .append("                              * 24                                                                                 ")
                .append("                           ) play_time                                                                             ")
                .append("                  FROM (SELECT start_time, end_time                                                                ")
                .append("                          FROM wxj_runplan_realtime_v                                                              ")
                .append("                         WHERE station_code IN (SELECT station_id                                                  ")
                .append("                                                  FROM wxj_station_info_t                                          ")
                .append("                                                 WHERE station_code = '" + reqMap.get("stationCode") + "')           ")
                .append("                           AND SYSDATE BETWEEN start_date AND end_date                                             ")
                .append("                           AND order_type IN ('D', 'F', 'I')                                                       ")
                .append("                           AND run_type = 1                                                                        ")
                .append("                           AND days LIKE                                                                           ")
                .append("                                     '%'                                                                           ")
                .append("                                  || (SELECT TO_CHAR (SYSDATE - 1, 'd')                                            ")
                .append("                                        FROM DUAL)                                                                 ")
                .append("                                  || '%')                                                                          ")
                .append("                 WHERE start_time > end_time AND start_time <= SYSDATE                                             ")
                .append("                UNION ALL                                                                                          ")
                .append("                SELECT COUNT (*) task_done,                                                                        ")
                .append("                       CEIL                                                                                        ")
                .append("                           (  SUM (  SYSDATE                                                                       ")
                .append("                                   - TO_DATE (   TO_CHAR (SYSDATE,                                                 ")
                .append("                                                          'yyyy-MM-dd'                                             ")
                .append("                                                         )                                                         ")
                .append("                                              || ' 00:00:00',                                                      ")
                .append("                                              'yyyy-MM-dd HH24:Mi:ss'                                              ")
                .append("                                             )                                                                     ")
                .append("                                  )                                                                                ")
                .append("                            * 24                                                                                   ")
                .append("                           ) play_time                                                                             ")
                .append("                  FROM (SELECT start_time, end_time                                                                ")
                .append("                          FROM wxj_runplan_realtime_v                                                              ")
                .append("                         WHERE station_code IN (SELECT station_id                                                  ")
                .append("                                                  FROM wxj_station_info_t                                          ")
                .append("                                                 WHERE station_code = '" + reqMap.get("stationCode") + "')           ")
                .append("                           AND SYSDATE BETWEEN start_date AND end_date                                             ")
                .append("                           AND order_type IN ('D', 'F', 'I')                                                       ")
                .append("                           AND run_type = 1                                                                        ")
                .append("                           AND days LIKE                                                                           ")
                .append("                                     '%'                                                                           ")
                .append("                                  || (SELECT TO_CHAR (SYSDATE - 1, 'd')                                            ")
                .append("                                        FROM DUAL)                                                                 ")
                .append("                                  || '%')                                                                          ")
                .append("                 WHERE start_time > end_time                                                                       ")
                .append("                   AND start_time > SYSDATE                                                                        ")
                .append("                   AND end_time > SYSDATE                                                                          ")
                .append("                UNION ALL                                                                                          ")
                .append("                SELECT COUNT (*) task_done,                                                                        ")
                .append("                       CEIL                                                                                        ")
                .append("                           (  SUM (  end_time                                                                      ")
                .append("                                   - TO_DATE (   TO_CHAR (SYSDATE,                                                 ")
                .append("                                                          'yyyy-MM-dd'                                             ")
                .append("                                                         )                                                         ")
                .append("                                              || ' 00:00:00',                                                      ")
                .append("                                              'yyyy-MM-dd HH24:Mi:ss'                                              ")
                .append("                                             )                                                                     ")
                .append("                                  )                                                                                ")
                .append("                            * 24                                                                                   ")
                .append("                           ) play_time                                                                             ")
                .append("                  FROM (SELECT start_time, end_time                                                                ")
                .append("                          FROM wxj_runplan_realtime_v                                                              ")
                .append("                         WHERE station_code IN (SELECT station_id                                                  ")
                .append("                                                  FROM wxj_station_info_t                                          ")
                .append("                                                 WHERE station_code = '" + reqMap.get("stationCode") + "')           ")
                .append("                           AND SYSDATE BETWEEN start_date AND end_date                                             ")
                .append("                           AND order_type IN ('D', 'F', 'I')                                                       ")
                .append("                           AND run_type = 1                                                                        ")
                .append("                           AND days LIKE                                                                           ")
                .append("                                     '%'                                                                           ")
                .append("                                  || (SELECT TO_CHAR (SYSDATE - 1, 'd')                                            ")
                .append("                                        FROM DUAL)                                                                 ")
                .append("                                  || '%')                                                                          ")
                .append("                 WHERE start_time > end_time                                                                       ")
                .append("                   AND start_time > SYSDATE                                                                        ")
                .append("                   AND end_time <= SYSDATE)) done                                                                  ")
                .append("       ON done.sql_type = total.param_value                                                                        ")
                .append("       LEFT JOIN                                                                                                   ")
                .append("       (SELECT 'today_station_tasks' sql_type, 0 stop_time                                                         ")
                .append("          FROM DUAL) STOP ON STOP.sql_type = total.param_value                                                     ")
                .append("       LEFT JOIN                                                                                                   ")
                .append("       (SELECT 'today_station_tasks' sql_type, COUNT (*) alarm_count                                               ")
                .append("          FROM wxj_alarm_realtime_t                                                                                ")
                .append("         WHERE station_code = '" + reqMap.get("stationCode") + "') alarm ON alarm.sql_type =                         ")
                .append("                                                             total.param_value                                     ")
                .append("       LEFT JOIN                                                                                                   ")
                .append("       (SELECT 'today_station_tasks' sql_type, COUNT (*) busiorder_count                                           ")
                .append("          FROM wxj_busiorder_total_realtime                                                                        ")
                .append("         WHERE station_code IN (SELECT station_id                                                                  ")
                .append("                                  FROM wxj_station_info_t                                                          ")
                .append("                                 WHERE station_code = '" + reqMap.get("stationCode") + "')                           ")
                .append("           AND order_code_dic NOT LIKE '台%') busiorder                                                            ")
                .append("       ON busiorder.sql_type = total.param_value                                                                   ")
                .append("       LEFT JOIN                                                                                                   ")
                .append("       (SELECT 'today_station_tasks' sql_type,                                                                     ")
                .append("               NVL (SUM (POWER), 0) power_doing                                                                    ")
                .append("          FROM (SELECT POWER                                                                                       ")
                .append("                  FROM wxj_runplan_realtime_v                                                                      ")
                .append("                 WHERE station_code IN (SELECT station_id                                                          ")
                .append("                                          FROM wxj_station_info_t                                                  ")
                .append("                                         WHERE station_code = '" + reqMap.get("stationCode") + "')                   ")
                .append("                   AND SYSDATE BETWEEN start_date AND end_date                                                     ")
                .append("                   AND order_type IN ('D', 'F', 'I')                                                               ")
                .append("                   AND run_type = 1                                                                                ")
                .append("                   AND days LIKE                                                                                   ")
                .append("                              '%' || (SELECT TO_CHAR (SYSDATE - 1, 'd')                                            ")
                .append("                                        FROM DUAL) || '%'                                                          ")
                .append("                   AND (   (    (start_time <= end_time)                                                           ")
                .append("                            AND (SYSDATE BETWEEN start_time AND end_time)                                          ")
                .append("                           )                                                                                       ")
                .append("                        OR (    (start_time > end_time)                                                            ")
                .append("                            AND (SYSDATE >= start_time OR SYSDATE <= end_time                                      ")
                .append("                                )                                                                                  ")
                .append("                           )                                                                                       ")
                .append("                       ))) doing ON doing.sql_type = total.param_value                                             ");
        return strBuffer.toString();
    }

    public static String getStationBasicInfo(Map reqMap) {
        StringBuffer strBuffer = new StringBuffer();
        strBuffer.append("SELECT station_name,unit_belong, unit_type, address, contacts_name, contacts_phone  ")
                .append("  FROM wxj_station_info_t                                                           ")
                .append(" WHERE station_code = '" + reqMap.get("stationCode") + "'                                                        ");
        return strBuffer.toString();
    }

    public static String getRunplanCompareInfo(Map reqMap) {
        StringBuffer strBuffer = new StringBuffer();
        strBuffer.append("SELECT station_count, freq_count, target_station_count, target_freq_count         ")
                .append("  FROM (SELECT *                                                                  ")
                .append("          FROM wxj_common_param_t                                                 ")
                .append("         WHERE param_type = 'today_station_tasks') total                          ")
                .append("       LEFT JOIN                                                                  ")
                .append("       (SELECT 'today_station_tasks' sql_type,                                    ")
                .append("               COUNT (DISTINCT station_name) target_station_count,                ")
                .append("               COUNT (DISTINCT station_name || '-' || freq) target_freq_count     ")
                .append("          FROM (SELECT station_name, freq,                                        ")
                .append("                       TO_DATE (   TO_CHAR (SYSDATE, 'yyyy-MM-dd')                ")
                .append("                                || TO_CHAR (start_time, ' HH24:Mi:ss'),           ")
                .append("                                'yyyy-MM-dd HH24:Mi:ss'                           ")
                .append("                               ) start_time,                                      ")
                .append("                       TO_DATE (   TO_CHAR (SYSDATE, 'yyyy-MM-dd')                ")
                .append("                                || TO_CHAR (end_time, ' HH24:Mi:ss'),             ")
                .append("                                'yyyy-MM-dd HH24:Mi:ss'                           ")
                .append("                               ) end_time                                         ")
                .append("                  FROM wxj_target_runplan_info_t                                  ")
                .append("                 WHERE SYSDATE BETWEEN start_date AND end_date                    ")
                .append("                   AND days LIKE                                                  ")
                .append("                              '%' || (SELECT TO_CHAR (SYSDATE - 1, 'd')           ")
                .append("                                        FROM DUAL) || '%')                        ")
                .append("         WHERE (   (    (start_time <= end_time)                                  ")
                .append("                    AND (SYSDATE BETWEEN start_time AND end_time)                 ")
                .append("                   )                                                              ")
                .append("                OR (    (start_time > end_time)                                   ")
                .append("                    AND (SYSDATE >= start_time OR SYSDATE <= end_time)            ")
                .append("                   )                                                              ")
                .append("               )) target ON target.sql_type = total.param_value                   ")
                .append("       LEFT JOIN                                                                  ")
                .append("       (SELECT 'today_station_tasks' sql_type,                                    ")
                .append("               COUNT (DISTINCT station_code) station_count,                       ")
                .append("               COUNT (DISTINCT station_code || '-' || freq) freq_count            ")
                .append("          FROM wxj_runplan_realtime_v                                             ")
                .append("         WHERE SYSDATE BETWEEN start_date AND end_date                            ")
                .append("           AND order_type IN ('I')                                                ")
                .append("           AND run_type = 1                                                       ")
                .append("           AND days LIKE '%' || (SELECT TO_CHAR (SYSDATE - 1, 'd')                ")
                .append("                                   FROM DUAL) || '%'                              ")
                .append("           AND (   (    (start_time <= end_time)                                  ")
                .append("                    AND (SYSDATE BETWEEN start_time AND end_time)                 ")
                .append("                   )                                                              ")
                .append("                OR (    (start_time > end_time)                                   ")
                .append("                    AND (SYSDATE >= start_time OR SYSDATE <= end_time)            ")
                .append("                   )                                                              ")
                .append("               )) china ON china.sql_type = total.param_value                     ");
        return strBuffer.toString();
    }

    public static String getRealTimeStationWorkStatus(Map reqMap) {
        StringBuffer strBuffer = new StringBuffer();
        strBuffer.append("SELECT   a.station_code, NVL (b.work_status, 'work') work_status                ")
                .append("    FROM wxj_station_info_t a                                                   ")
                .append("         LEFT JOIN                                                              ")
                .append("         (SELECT station_code,                                                  ")
                .append("                 CASE                                                           ")
                .append("                    WHEN work_status = '2'                                        ")
                .append("                       THEN 'free'                                               ")
                .append("                    WHEN work_status = '3'                                        ")
                .append("                       THEN 'bad'                                               ")
                .append("                    WHEN work_status = '4'                                        ")
                .append("                       THEN 'fix'                                              ")
                .append("                    ELSE 'work'                                                 ")
                .append("                 END work_status                                                ")
                .append("            FROM (SELECT   station_code, max (work_status) work_status          ")
                .append("                      FROM (SELECT station_code,                                ")
                .append("                                   DECODE (SUBSTR (work_status, 1, 1),          ")
                .append("                                           '1', '7',                            ")
                .append("                                           '2', '2',                            ")
                .append("                                           '3', '3',                            ")
                .append("                                           '4', '4',                           ")
                .append("                                           'error'                              ")
                .append("                                          ) work_status                         ")
                .append("                              FROM wxj_transmitter_status_t                     ")
                .append("                             WHERE LENGTH (station_code) = 2)                   ")
                .append("                     WHERE work_status <> 'error'                               ")
                .append("                  GROUP BY station_code)) b ON a.station_id = b.station_code    ")
                .append("ORDER BY station_code                                                           ");
        return strBuffer.toString();
    }
}
